export const caseSchema = {
  name: 'case',
  title: 'Caso / Dictamen Pericial',
  type: 'document',
  fields: [
    {
      name: 'brand',
      title: 'Marca',
      type: 'string',
      options: { list: ['CNP', 'Peritus'] },
      initialValue: 'CNP',
    },
    {
      name: 'caseCode',
      title: 'Codigo de Caso',
      type: 'string',
      description: 'Auto-generado: CNP-YYYY-NNNN o PER-YYYY-NNNN',
      readOnly: true,
    },
    { name: 'title', title: 'Titulo', type: 'string', validation: (Rule: { required: () => unknown }) => Rule.required() },
    { name: 'description', title: 'Descripcion', type: 'text' },
    {
      name: 'client',
      title: 'Cliente',
      type: 'reference',
      to: [{ type: 'crmClient' }],
    },
    {
      name: 'commercial',
      title: 'Asesor Comercial',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    {
      name: 'technicalAnalyst',
      title: 'Analista Tecnico',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    {
      name: 'assignedExpert',
      title: 'Perito Asignado',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    {
      name: 'assignedFinanciero',
      title: 'Financiero Asignado',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    {
      name: 'discipline',
      title: 'Disciplina',
      type: 'string',
      options: {
        list: [
          { title: 'Financiero', value: 'financiero' },
          { title: 'Medico', value: 'medico' },
          { title: 'Grafologia', value: 'grafologia' },
          { title: 'Ingenieria', value: 'ingenieria' },
          { title: 'Arquitectura', value: 'arquitectura' },
          { title: 'Contable', value: 'contable' },
          { title: 'Ambiental', value: 'ambiental' },
          { title: 'Informatico', value: 'informatico' },
          { title: 'Valuacion', value: 'valuacion' },
          { title: 'Otro', value: 'otro' },
        ],
      },
    },
    {
      name: 'status',
      title: 'Estado',
      type: 'string',
      initialValue: 'creado',
      options: {
        list: [
          { title: 'Creado', value: 'creado' },
          { title: 'Gestionado', value: 'gestionado' },
          { title: 'Cancelado', value: 'cancelado' },
        ],
      },
    },
    {
      name: 'complexity',
      title: 'Complejidad',
      type: 'string',
      initialValue: 'media',
      options: {
        list: [
          { title: 'Baja', value: 'baja' },
          { title: 'Media', value: 'media' },
          { title: 'Alta', value: 'alta' },
          { title: 'Critica', value: 'critica' },
        ],
      },
    },
    {
      name: 'priority',
      title: 'Prioridad',
      type: 'string',
      initialValue: 'normal',
      options: {
        list: [
          { title: 'Baja', value: 'baja' },
          { title: 'Normal', value: 'normal' },
          { title: 'Alta', value: 'alta' },
          { title: 'Urgente', value: 'urgente' },
        ],
      },
    },
    { name: 'estimatedAmount', title: 'Monto Estimado', type: 'number' },
    { name: 'hasHearing', title: 'Tendra Audiencia', type: 'boolean', initialValue: false },
    { name: 'hearingDate', title: 'Fecha de Audiencia', type: 'datetime' },
    { name: 'hearingLink', title: 'Enlace de Audiencia', type: 'url' },
    { name: 'deadlineDate', title: 'Fecha Limite', type: 'datetime' },
    { name: 'city', title: 'Ciudad', type: 'string' },
    { name: 'courtName', title: 'Juzgado', type: 'string' },
    { name: 'caseNumber', title: 'Numero de Radicado', type: 'string' },
    { name: 'riskScore', title: 'Puntaje de Riesgo', type: 'number' },
    {
      name: 'statusChangedByRole',
      title: 'Estado Cambiado Por Rol',
      type: 'string',
      description: 'Rol del ultimo usuario que cambio el estado. Controla la cadena juridico→financiero→admin.',
    },
    {
      name: 'createdBy',
      title: 'Creado Por',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
  ],
};
