export const quoteSchema = {
  name: 'quote',
  title: 'Cotizacion',
  type: 'document',
  fields: [
    {
      name: 'case',
      title: 'Caso',
      type: 'reference',
      to: [{ type: 'case' }],
    },
    { name: 'version', title: 'Version', type: 'number', initialValue: 1 },
    { name: 'totalPrice', title: 'Precio Total', type: 'number' },
    { name: 'discountPercentage', title: 'Descuento (%)', type: 'number', initialValue: 0 },
    { name: 'finalValue', title: 'Valor Final', type: 'number' },
    {
      name: 'status',
      title: 'Estado',
      type: 'string',
      initialValue: 'borrador',
      options: {
        list: [
          { title: 'Borrador', value: 'borrador' },
          { title: 'Enviada', value: 'enviada' },
          { title: 'Aprobada', value: 'aprobada' },
          { title: 'Rechazada', value: 'rechazada' },
          { title: 'Expirada', value: 'expirada' },
        ],
      },
    },
    { name: 'validUntil', title: 'Valida Hasta', type: 'datetime' },
    { name: 'sentAt', title: 'Enviada En', type: 'datetime' },
    { name: 'approvedAt', title: 'Aprobada En', type: 'datetime' },
    {
      name: 'approvedBy',
      title: 'Aprobada Por',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    { name: 'rejectionReason', title: 'Razon de Rechazo', type: 'text' },
    { name: 'notes', title: 'Notas', type: 'text' },
    {
      name: 'createdBy',
      title: 'Creado Por',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    { name: 'quoteDocument', title: 'Documento de Cotizacion', type: 'file' },
    { name: 'firstPaymentDate', title: 'Fecha Primer Pago', type: 'datetime' },
    { name: 'lastPaymentDate', title: 'Fecha Ultimo Pago', type: 'datetime' },
    { name: 'firstPaymentPercentage', title: 'Porcentaje Primer Pago', type: 'number', initialValue: 50 },
    { name: 'customSplit', title: 'Division Personalizada', type: 'boolean', initialValue: false },
  ],
};
