export const quoteSchema = {
  name: 'quote',
  title: 'Cotizacion',
  type: 'document',
  fields: [
    {
      name: 'case',
      title: 'Caso',
      type: 'reference',
      to: [{ type: 'case' }],
    },
    { name: 'version', title: 'Version', type: 'number', initialValue: 1 },
    { name: 'estimatedHours', title: 'Horas Estimadas', type: 'number' },
    { name: 'hourlyRate', title: 'Tarifa por Hora', type: 'number' },
    { name: 'baseValue', title: 'Valor Base', type: 'number' },
    { name: 'expenses', title: 'Gastos', type: 'number', initialValue: 0 },
    { name: 'marginPercentage', title: 'Margen (%)', type: 'number', initialValue: 30 },
    { name: 'totalValue', title: 'Valor Total', type: 'number' },
    { name: 'discountPercentage', title: 'Descuento (%)', type: 'number', initialValue: 0 },
    { name: 'finalValue', title: 'Valor Final', type: 'number' },
    {
      name: 'status',
      title: 'Estado',
      type: 'string',
      initialValue: 'borrador',
      options: {
        list: [
          { title: 'Borrador', value: 'borrador' },
          { title: 'Enviada', value: 'enviada' },
          { title: 'Aprobada', value: 'aprobada' },
          { title: 'Rechazada', value: 'rechazada' },
          { title: 'Expirada', value: 'expirada' },
        ],
      },
    },
    { name: 'validUntil', title: 'Valida Hasta', type: 'datetime' },
    { name: 'sentAt', title: 'Enviada En', type: 'datetime' },
    { name: 'approvedAt', title: 'Aprobada En', type: 'datetime' },
    {
      name: 'approvedBy',
      title: 'Aprobada Por',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
    { name: 'rejectionReason', title: 'Razon de Rechazo', type: 'text' },
    { name: 'notes', title: 'Notas', type: 'text' },
    {
      name: 'createdBy',
      title: 'Creado Por',
      type: 'reference',
      to: [{ type: 'crmUser' }],
    },
  ],
};
