export const COLOMBIA_CITIES = [
  "Bogota D.C.",
  "Medellin",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cucuta",
  "Bucaramanga",
  "Pereira",
  "Santa Marta",
  "Ibague",
  "Pasto",
  "Manizales",
  "Neiva",
  "Villavicencio",
  "Armenia",
  "Valledupar",
  "Monteria",
  "Sincelejo",
  "Popayan",
  "Tunja",
  "Floridablanca",
  "Soledad",
  "Itagui",
  "Soacha",
  "Buenaventura",
  "Palmira",
  "Envigado",
  "Bello",
  "Tulua",
  "Dosquebradas",
  "Riohacha",
  "Apartado",
  "Quibdo",
  "Sogamoso",
  "Barrancabermeja",
  "Girardot",
  "Yopal",
  "Duitama",
  "Florencia",
  "Zipaquira",
  "Cartago",
  "Girón",
  "Piedecuesta",
  "Maicao",
  "Magangue",
  "Turbo",
  "Facatativa",
  "Fusagasuga",
  "Ocana",
  "Aguachica",
  "Lorica",
  "Sahagún",
  "Caucasia",
  "Chiquinquira",
  "Ciénaga",
  "Fundacion",
  "El Carmen de Bolivar",
  "Puerto Berrio",
  "La Dorada",
  "Espinal",
  "Leticia",
  "Mocoa",
  "San Andres",
  "Arauca",
  "Inirida",
  "Mitu",
  "Puerto Carreño",
  "San Jose del Guaviare",
  "Rionegro",
  "La Ceja",
  "Marinilla",
  "Sabaneta",
  "Copacabana",
  "Caldas",
  "Barbosa",
  "Chia",
  "Cajica",
  "Cota",
  "Mosquera",
  "Funza",
  "Madrid",
  "Tocancipa",
  "La Calera",
  "Tabio",
  "Tenjo",
  "Sopó",
  "Gachancipa",
  "Sibate",
  "Silvania",
  "Villeta",
  "La Mesa",
  "Acacias",
  "Granada",
  "San Martin",
  "Puerto Lopez",
  "Chaparral",
  "Melgar",
  "Honda",
  "Mariquita",
  "Libano",
  "Lerida",
  "Guamo",
  "Garzon",
  "Pitalito",
  "La Plata",
  "Campoalegre",
  "Santander de Quilichao",
  "Puerto Tejada",
  "Piendamo",
  "El Bordo",
  "Ipiales",
  "Tumaco",
  "La Union",
  "Samaniego",
  "Tuquerres",
  "Buga",
  "Sevilla",
  "Caicedonia",
  "Zarzal",
  "Roldanillo",
  "Jamundi",
  "Yumbo",
  "Candelaria",
  "Florida",
  "Pradera",
  "El Cerrito",
  "Calarca",
  "Circasia",
  "La Tebaida",
  "Montenegro",
  "Chinchina",
  "Villamaria",
  "Neira",
  "Anserma",
  "Riosucio",
  "Santa Rosa de Cabal",
  "Marsella",
  "La Virginia",
  "Belen de Umbria",
  "Pamplona",
  "Los Patios",
  "Villa del Rosario",
  "El Zulia",
  "Tibu",
  "San Gil",
  "Socorro",
  "Barbosa",
  "Velez",
  "Malaga",
  "Sabana de Torres",
  "Lebrija",
  "San Vicente de Chucuri",
  "Chinu",
  "San Marcos",
  "San Onofre",
  "Tolu",
  "Coveñas",
  "Ovejas",
  "Corozal",
  "San Juan Nepomuceno",
  "Arjona",
  "Turbaco",
  "San Jacinto",
  "Carmen de Apicala",
  "Plato",
  "El Banco",
  "Ariguani",
  "Zona Bananera",
  "Codazzi",
  "La Jagua de Ibirico",
  "Bosconia",
  "San Juan del Cesar",
  "Fonseca",
  "Villanueva",
  "Urumita",
  "Planeta Rica",
  "Cerete",
  "Montelibano",
  "Tierralta",
  "San Pelayo",
  "San Carlos",
  "Chigorodo",
  "Carepa",
  "Necocli",
  "San Pedro de Uraba",
  "Yarumal",
  "Santa Rosa de Osos",
  "Don Matias",
  "Amaga",
  "Andes",
  "Ciudad Bolivar",
  "Jardin",
  "Jerico",
  "Tamesis",
  "Fredonia",
  "La Estrella",
  "Girardota",
  "San Pedro de los Milagros",
  "Entrerrios",
  "Santa Fe de Antioquia",
  "Puerto Boyaca",
  "Paipa",
  "Villa de Leyva",
  "Moniquira",
  "Samaca",
  "Ventaquemada",
  "Combita",
  "Toca",
  "Nobsa",
  "Tibasosa",
  "Firavitoba",
  "Corrales",
  "Paz de Ariporo",
  "Tame",
  "Saravena",
  "Fortul",
] as const;
